import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Nav } from "./_nav/Nav";
import { Page, Section } from "./_ui";
import { Introduction } from "./_introduction/Introduction";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-slate-800 text-slate-100 ${roboto.className}`}>
        <Nav />
        <Page>
          <Section>
            <Introduction />
            <span className="h-6" />
          </Section>
          {children}
        </Page>
      </body>
    </html>
  );
}
