import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import AppBar from "./_nav/Nav/Nav";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-slate-800 text-slate-100 ${roboto.className}`}>
        <AppBar>hello</AppBar>
        {children}
      </body>
    </html>
  );
}
